//! Static access to the pre-built plenum bundle.

/// The concatenated plenum.js bundle: `require()` resolver + every
/// registered polyfill, ready to `eval` inside a QuickJS context.
///
/// Contents are generated by `build.rs`. The embedded string is the
/// single source of truth at runtime — no file system access, no bundler
/// on the hot path.
pub const PLENUM_BUNDLE: &str = include_str!("../generated/plenum_bundle.js");
